// Code generated by bestiary-gen. DO NOT EDIT.

package bestiary

// Family identifies the model family from the models.dev API.
// It is a named string type for type safety, following the same pattern as Provider.
type Family string

const (
	FamilyHy                Family = "Hy"
	FamilyAgi               Family = "agi"
	FamilyAllenai           Family = "allenai"
	FamilyAlpha             Family = "alpha"
	FamilyAuto              Family = "auto"
	FamilyBaichuan          Family = "baichuan"
	FamilyBge               Family = "bge"
	FamilyBigPickle         Family = "big-pickle"
	FamilyCanopylabs        Family = "canopylabs"
	FamilyChutesai          Family = "chutesai"
	FamilyClaude            Family = "claude"
	FamilyClaudeFable       Family = "claude-fable"
	FamilyClaudeHaiku       Family = "claude-haiku"
	FamilyClaudeMythos      Family = "claude-mythos"
	FamilyClaudeOpus        Family = "claude-opus"
	FamilyClaudeSonnet      Family = "claude-sonnet"
	FamilyCodestral         Family = "codestral"
	FamilyCodestralEmbed    Family = "codestral-embed"
	FamilyCogito            Family = "cogito"
	FamilyCohereEmbed       Family = "cohere-embed"
	FamilyCommand           Family = "command"
	FamilyCommandA          Family = "command-a"
	FamilyCommandR          Family = "command-r"
	FamilyDallE             Family = "dall-e"
	FamilyDeepSeek          Family = "deepseek"
	FamilyDeepSeekFlash     Family = "deepseek-flash"
	FamilyDeepSeekThinking  Family = "deepseek-thinking"
	FamilyDevstral          Family = "devstral"
	FamilyElevenlabs        Family = "elevenlabs"
	FamilyErnie             Family = "ernie"
	FamilyFlux              Family = "flux"
	FamilyFugu              Family = "fugu"
	FamilyGemini            Family = "gemini"
	FamilyGeminiFlash       Family = "gemini-flash"
	FamilyGeminiFlashLite   Family = "gemini-flash-lite"
	FamilyGeminiPro         Family = "gemini-pro"
	FamilyGemma             Family = "gemma"
	FamilyGLM               Family = "glm"
	FamilyGLMAir            Family = "glm-air"
	FamilyGLMFlash          Family = "glm-flash"
	FamilyGLMFree           Family = "glm-free"
	FamilyGLMZ              Family = "glm-z"
	FamilyGlmv              Family = "glmv"
	FamilyGPT               Family = "gpt"
	FamilyGPTCodex          Family = "gpt-codex"
	FamilyGPTCodexMini      Family = "gpt-codex-mini"
	FamilyGPTCodexSpark     Family = "gpt-codex-spark"
	FamilyGPTImage          Family = "gpt-image"
	FamilyGPTLuna           Family = "gpt-luna"
	FamilyGPTMini           Family = "gpt-mini"
	FamilyGPTNano           Family = "gpt-nano"
	FamilyGPTOss            Family = "gpt-oss"
	FamilyGPTPro            Family = "gpt-pro"
	FamilyGPTSol            Family = "gpt-sol"
	FamilyGPTTerra          Family = "gpt-terra"
	FamilyGranite           Family = "granite"
	FamilyGrok              Family = "grok"
	FamilyGrokBuild         Family = "grok-build"
	FamilyGroq              Family = "groq"
	FamilyHermes            Family = "hermes"
	FamilyHunyuan           Family = "hunyuan"
	FamilyHy3Free           Family = "hy3-free"
	FamilyIdeogram          Family = "ideogram"
	FamilyImagen            Family = "imagen"
	FamilyJamba             Family = "jamba"
	FamilyKatCoder          Family = "kat-coder"
	FamilyKimi              Family = "kimi"
	FamilyKimiFree          Family = "kimi-free"
	FamilyKimiK2            Family = "kimi-k2"
	FamilyKimiK3            Family = "kimi-k3"
	FamilyKimiThinking      Family = "kimi-thinking"
	FamilyLaguna            Family = "laguna"
	FamilyLagunaS           Family = "laguna-s"
	FamilyLing              Family = "ling"
	FamilyLingFlashFree     Family = "ling-flash-free"
	FamilyLiquid            Family = "liquid"
	FamilyLlama             Family = "llama"
	FamilyLongcat           Family = "longcat"
	FamilyLucid             Family = "lucid"
	FamilyLyria             Family = "lyria"
	FamilyMagistral         Family = "magistral"
	FamilyMagistralMedium   Family = "magistral-medium"
	FamilyMagistralSmall    Family = "magistral-small"
	FamilyMai               Family = "mai"
	FamilyMercury           Family = "mercury"
	FamilyMimo              Family = "mimo"
	FamilyMimoFlashFree     Family = "mimo-flash-free"
	FamilyMimoOmniFree      Family = "mimo-omni-free"
	FamilyMimoProFree       Family = "mimo-pro-free"
	FamilyMimoV2Omni        Family = "mimo-v2-omni"
	FamilyMimoV2Pro         Family = "mimo-v2-pro"
	FamilyMimoV25           Family = "mimo-v2.5"
	FamilyMimoV25Free       Family = "mimo-v2.5-free"
	FamilyMimoV25Pro        Family = "mimo-v2.5-pro"
	FamilyMiniMax           Family = "minimax"
	FamilyMiniMaxFree       Family = "minimax-free"
	FamilyMiniMaxM25        Family = "minimax-m2.5"
	FamilyMiniMaxM27        Family = "minimax-m2.7"
	FamilyMiniMaxM3         Family = "minimax-m3"
	FamilyMiniMaxM3Free     Family = "minimax-m3-free"
	FamilyMinistral         Family = "ministral"
	FamilyMistral           Family = "mistral"
	FamilyMistralEmbed      Family = "mistral-embed"
	FamilyMistralLarge      Family = "mistral-large"
	FamilyMistralMedium     Family = "mistral-medium"
	FamilyMistralNemo       Family = "mistral-nemo"
	FamilyMistralSmall      Family = "mistral-small"
	FamilyMixtral           Family = "mixtral"
	FamilyMmPoly            Family = "mm-poly"
	FamilyModelRouter       Family = "model-router"
	FamilyMorph             Family = "morph"
	FamilyMuse              Family = "muse"
	FamilyMuseFree          Family = "muse-free"
	FamilyNanoBanana        Family = "nano-banana"
	FamilyNemotron          Family = "nemotron"
	FamilyNemotronFree      Family = "nemotron-free"
	FamilyNorth             Family = "north"
	FamilyNorthFree         Family = "north-free"
	FamilyNousresearch      Family = "nousresearch"
	FamilyNova              Family = "nova"
	FamilyNovaLite          Family = "nova-lite"
	FamilyNovaMicro         Family = "nova-micro"
	FamilyNovaPro           Family = "nova-pro"
	FamilyO                 Family = "o"
	FamilyOMini             Family = "o-mini"
	FamilyOPro              Family = "o-pro"
	FamilyOrnith            Family = "ornith"
	FamilyOsmosis           Family = "osmosis"
	FamilyPalmyra           Family = "palmyra"
	FamilyPhi               Family = "phi"
	FamilyPixtral           Family = "pixtral"
	FamilyQvq               Family = "qvq"
	FamilyQwen              Family = "qwen"
	FamilyQwenFree          Family = "qwen-free"
	FamilyQwen35            Family = "qwen3.5"
	FamilyQwen36            Family = "qwen3.6"
	FamilyQwen37Max         Family = "qwen3.7-max"
	FamilyQwen37Plus        Family = "qwen3.7-plus"
	FamilyQwen38Max         Family = "qwen3.8-max"
	FamilyQwerky            Family = "qwerky"
	FamilyRay               Family = "ray"
	FamilyRecraft           Family = "recraft"
	FamilyReka              Family = "reka"
	FamilyRing              Family = "ring"
	FamilyRing1TFree        Family = "ring-1t-free"
	FamilyRnj               Family = "rnj"
	FamilyRunway            Family = "runway"
	FamilySakanaNamazu      Family = "sakana-namazu"
	FamilySarvam            Family = "sarvam"
	FamilySeed              Family = "seed"
	FamilySolar             Family = "solar"
	FamilySolarMini         Family = "solar-mini"
	FamilySolarPro          Family = "solar-pro"
	FamilySonar             Family = "sonar"
	FamilySonarDeepResearch Family = "sonar-deep-research"
	FamilySonarPro          Family = "sonar-pro"
	FamilySonarReasoning    Family = "sonar-reasoning"
	FamilySora              Family = "sora"
	FamilyStableDiffusion   Family = "stable-diffusion"
	FamilyStep              Family = "step"
	FamilyTako              Family = "tako"
	FamilyTextEmbedding     Family = "text-embedding"
	FamilyTitanEmbed        Family = "titan-embed"
	FamilyTopazlabs         Family = "topazlabs"
	FamilyTrinity           Family = "trinity"
	FamilyUnsloth           Family = "unsloth"
	FamilyV0                Family = "v0"
	FamilyVenice            Family = "venice"
	FamilyVeo               Family = "veo"
	FamilyVoxtral           Family = "voxtral"
	FamilyVoyage            Family = "voyage"
	FamilyWhisper           Family = "whisper"
	FamilyYi                Family = "yi"
)

// allFamilies is the complete list of family values from the models.dev API.
var allFamilies = [...]Family{
	"Hy",
	"agi",
	"allenai",
	"alpha",
	"auto",
	"baichuan",
	"bge",
	"big-pickle",
	"canopylabs",
	"chutesai",
	"claude",
	"claude-fable",
	"claude-haiku",
	"claude-mythos",
	"claude-opus",
	"claude-sonnet",
	"codestral",
	"codestral-embed",
	"cogito",
	"cohere-embed",
	"command",
	"command-a",
	"command-r",
	"dall-e",
	"deepseek",
	"deepseek-flash",
	"deepseek-thinking",
	"devstral",
	"elevenlabs",
	"ernie",
	"flux",
	"fugu",
	"gemini",
	"gemini-flash",
	"gemini-flash-lite",
	"gemini-pro",
	"gemma",
	"glm",
	"glm-air",
	"glm-flash",
	"glm-free",
	"glm-z",
	"glmv",
	"gpt",
	"gpt-codex",
	"gpt-codex-mini",
	"gpt-codex-spark",
	"gpt-image",
	"gpt-luna",
	"gpt-mini",
	"gpt-nano",
	"gpt-oss",
	"gpt-pro",
	"gpt-sol",
	"gpt-terra",
	"granite",
	"grok",
	"grok-build",
	"groq",
	"hermes",
	"hunyuan",
	"hy3-free",
	"ideogram",
	"imagen",
	"jamba",
	"kat-coder",
	"kimi",
	"kimi-free",
	"kimi-k2",
	"kimi-k3",
	"kimi-thinking",
	"laguna",
	"laguna-s",
	"ling",
	"ling-flash-free",
	"liquid",
	"llama",
	"longcat",
	"lucid",
	"lyria",
	"magistral",
	"magistral-medium",
	"magistral-small",
	"mai",
	"mercury",
	"mimo",
	"mimo-flash-free",
	"mimo-omni-free",
	"mimo-pro-free",
	"mimo-v2-omni",
	"mimo-v2-pro",
	"mimo-v2.5",
	"mimo-v2.5-free",
	"mimo-v2.5-pro",
	"minimax",
	"minimax-free",
	"minimax-m2.5",
	"minimax-m2.7",
	"minimax-m3",
	"minimax-m3-free",
	"ministral",
	"mistral",
	"mistral-embed",
	"mistral-large",
	"mistral-medium",
	"mistral-nemo",
	"mistral-small",
	"mixtral",
	"mm-poly",
	"model-router",
	"morph",
	"muse",
	"muse-free",
	"nano-banana",
	"nemotron",
	"nemotron-free",
	"north",
	"north-free",
	"nousresearch",
	"nova",
	"nova-lite",
	"nova-micro",
	"nova-pro",
	"o",
	"o-mini",
	"o-pro",
	"ornith",
	"osmosis",
	"palmyra",
	"phi",
	"pixtral",
	"qvq",
	"qwen",
	"qwen-free",
	"qwen3.5",
	"qwen3.6",
	"qwen3.7-max",
	"qwen3.7-plus",
	"qwen3.8-max",
	"qwerky",
	"ray",
	"recraft",
	"reka",
	"ring",
	"ring-1t-free",
	"rnj",
	"runway",
	"sakana-namazu",
	"sarvam",
	"seed",
	"solar",
	"solar-mini",
	"solar-pro",
	"sonar",
	"sonar-deep-research",
	"sonar-pro",
	"sonar-reasoning",
	"sora",
	"stable-diffusion",
	"step",
	"tako",
	"text-embedding",
	"titan-embed",
	"topazlabs",
	"trinity",
	"unsloth",
	"v0",
	"venice",
	"veo",
	"voxtral",
	"voyage",
	"whisper",
	"yi",
}

// Families returns all known Family values as a defensive copy.
func Families() []Family {
	out := make([]Family, len(allFamilies))
	copy(out, allFamilies[:])
	return out
}
