// Code generated by bestiary-gen. DO NOT EDIT.

package bestiary

// Family is the raw API family string for a model.
type Family = string

const (
	FamilyAllam             Family = "allam"
	FamilyAllenai           Family = "allenai"
	FamilyAura              Family = "aura"
	FamilyAuto              Family = "auto"
	FamilyBaichuan          Family = "baichuan"
	FamilyBart              Family = "bart"
	FamilyBge               Family = "bge"
	FamilyBigPickle         Family = "big-pickle"
	FamilyCanopylabs        Family = "canopylabs"
	FamilyChutesai          Family = "chutesai"
	FamilyClaude            Family = "claude"
	FamilyClaudeHaiku       Family = "claude-haiku"
	FamilyClaudeOpus        Family = "claude-opus"
	FamilyClaudeSonnet      Family = "claude-sonnet"
	FamilyCodestral         Family = "codestral"
	FamilyCodestralEmbed    Family = "codestral-embed"
	FamilyCogito            Family = "cogito"
	FamilyCohereEmbed       Family = "cohere-embed"
	FamilyCommand           Family = "command"
	FamilyCommandA          Family = "command-a"
	FamilyCommandR          Family = "command-r"
	FamilyDallE             Family = "dall-e"
	FamilyDeepseek          Family = "deepseek"
	FamilyDeepseekThinking  Family = "deepseek-thinking"
	FamilyDevstral          Family = "devstral"
	FamilyDistilbert        Family = "distilbert"
	FamilyElevenlabs        Family = "elevenlabs"
	FamilyErnie             Family = "ernie"
	FamilyFlux              Family = "flux"
	FamilyGemini            Family = "gemini"
	FamilyGeminiEmbedding   Family = "gemini-embedding"
	FamilyGeminiFlash       Family = "gemini-flash"
	FamilyGeminiFlashLite   Family = "gemini-flash-lite"
	FamilyGeminiPro         Family = "gemini-pro"
	FamilyGemma             Family = "gemma"
	FamilyGlm               Family = "glm"
	FamilyGlmAir            Family = "glm-air"
	FamilyGlmFlash          Family = "glm-flash"
	FamilyGlmFree           Family = "glm-free"
	FamilyGlmZ              Family = "glm-z"
	FamilyGlmv              Family = "glmv"
	FamilyGPT               Family = "gpt"
	FamilyGPTCodex          Family = "gpt-codex"
	FamilyGPTCodexMini      Family = "gpt-codex-mini"
	FamilyGPTCodexSpark     Family = "gpt-codex-spark"
	FamilyGPTImage          Family = "gpt-image"
	FamilyGPTMini           Family = "gpt-mini"
	FamilyGPTNano           Family = "gpt-nano"
	FamilyGPTOss            Family = "gpt-oss"
	FamilyGPTPro            Family = "gpt-pro"
	FamilyGranite           Family = "granite"
	FamilyGrok              Family = "grok"
	FamilyGrokBeta          Family = "grok-beta"
	FamilyGrokVision        Family = "grok-vision"
	FamilyGroq              Family = "groq"
	FamilyHermes            Family = "hermes"
	FamilyHunyuan           Family = "hunyuan"
	FamilyIdeogram          Family = "ideogram"
	FamilyImagen            Family = "imagen"
	FamilyIndictrans        Family = "indictrans"
	FamilyIntellect         Family = "intellect"
	FamilyJais              Family = "jais"
	FamilyJamba             Family = "jamba"
	FamilyKatCoder          Family = "kat-coder"
	FamilyKimi              Family = "kimi"
	FamilyKimiFree          Family = "kimi-free"
	FamilyKimiThinking      Family = "kimi-thinking"
	FamilyLing              Family = "ling"
	FamilyLiquid            Family = "liquid"
	FamilyLlama             Family = "llama"
	FamilyLongcat           Family = "longcat"
	FamilyLucid             Family = "lucid"
	FamilyLyria             Family = "lyria"
	FamilyM2m               Family = "m2m"
	FamilyMagistral         Family = "magistral"
	FamilyMagistralMedium   Family = "magistral-medium"
	FamilyMagistralSmall    Family = "magistral-small"
	FamilyMai               Family = "mai"
	FamilyMelotts           Family = "melotts"
	FamilyMercury           Family = "mercury"
	FamilyMimo              Family = "mimo"
	FamilyMimoFlashFree     Family = "mimo-flash-free"
	FamilyMimoOmni          Family = "mimo-omni"
	FamilyMimoOmniFree      Family = "mimo-omni-free"
	FamilyMimoPro           Family = "mimo-pro"
	FamilyMimoProFree       Family = "mimo-pro-free"
	FamilyMinimax           Family = "minimax"
	FamilyMinimaxFree       Family = "minimax-free"
	FamilyMinimaxM25        Family = "minimax-m2.5"
	FamilyMinimaxM27        Family = "minimax-m2.7"
	FamilyMinistral         Family = "ministral"
	FamilyMistral           Family = "mistral"
	FamilyMistralEmbed      Family = "mistral-embed"
	FamilyMistralLarge      Family = "mistral-large"
	FamilyMistralMedium     Family = "mistral-medium"
	FamilyMistralNemo       Family = "mistral-nemo"
	FamilyMistralSmall      Family = "mistral-small"
	FamilyMixtral           Family = "mixtral"
	FamilyMmPoly            Family = "mm-poly"
	FamilyModelRouter       Family = "model-router"
	FamilyMorph             Family = "morph"
	FamilyNanoBanana        Family = "nano-banana"
	FamilyNemoretriever     Family = "nemoretriever"
	FamilyNemotron          Family = "nemotron"
	FamilyNemotronFree      Family = "nemotron-free"
	FamilyNousresearch      Family = "nousresearch"
	FamilyNova              Family = "nova"
	FamilyNovaLite          Family = "nova-lite"
	FamilyNovaMicro         Family = "nova-micro"
	FamilyNovaPro           Family = "nova-pro"
	FamilyO                 Family = "o"
	FamilyOMini             Family = "o-mini"
	FamilyOPro              Family = "o-pro"
	FamilyOpengvlab         Family = "opengvlab"
	FamilyOsmosis           Family = "osmosis"
	FamilyPalmyra           Family = "palmyra"
	FamilyPangu             Family = "pangu"
	FamilyParakeet          Family = "parakeet"
	FamilyPhi               Family = "phi"
	FamilyPixtral           Family = "pixtral"
	FamilyPlamo             Family = "plamo"
	FamilyQvq               Family = "qvq"
	FamilyQwen              Family = "qwen"
	FamilyQwenFree          Family = "qwen-free"
	FamilyQwerky            Family = "qwerky"
	FamilyRay               Family = "ray"
	FamilyRecraft           Family = "recraft"
	FamilyRednote           Family = "rednote"
	FamilyRing              Family = "ring"
	FamilyRnj               Family = "rnj"
	FamilyRunway            Family = "runway"
	FamilySeed              Family = "seed"
	FamilySkywork           Family = "skywork"
	FamilySmartTurn         Family = "smart-turn"
	FamilySolarMini         Family = "solar-mini"
	FamilySolarPro          Family = "solar-pro"
	FamilySonar             Family = "sonar"
	FamilySonarDeepResearch Family = "sonar-deep-research"
	FamilySonarPro          Family = "sonar-pro"
	FamilySonarReasoning    Family = "sonar-reasoning"
	FamilySora              Family = "sora"
	FamilySourceful         Family = "sourceful"
	FamilyStableDiffusion   Family = "stable-diffusion"
	FamilyStep              Family = "step"
	FamilyTako              Family = "tako"
	FamilyTextEmbedding     Family = "text-embedding"
	FamilyTitanEmbed        Family = "titan-embed"
	FamilyTngtech           Family = "tngtech"
	FamilyTopazlabs         Family = "topazlabs"
	FamilyTrinity           Family = "trinity"
	FamilyTrinityMini       Family = "trinity-mini"
	FamilyUnsloth           Family = "unsloth"
	FamilyV0                Family = "v0"
	FamilyVenice            Family = "venice"
	FamilyVeo               Family = "veo"
	FamilyVoxtral           Family = "voxtral"
	FamilyVoyage            Family = "voyage"
	FamilyWhisper           Family = "whisper"
	FamilyYi                Family = "yi"
)

// allFamilies is the complete list of family values from the models.dev API.
var allFamilies = [...]Family{
	"allam",
	"allenai",
	"aura",
	"auto",
	"baichuan",
	"bart",
	"bge",
	"big-pickle",
	"canopylabs",
	"chutesai",
	"claude",
	"claude-haiku",
	"claude-opus",
	"claude-sonnet",
	"codestral",
	"codestral-embed",
	"cogito",
	"cohere-embed",
	"command",
	"command-a",
	"command-r",
	"dall-e",
	"deepseek",
	"deepseek-thinking",
	"devstral",
	"distilbert",
	"elevenlabs",
	"ernie",
	"flux",
	"gemini",
	"gemini-embedding",
	"gemini-flash",
	"gemini-flash-lite",
	"gemini-pro",
	"gemma",
	"glm",
	"glm-air",
	"glm-flash",
	"glm-free",
	"glm-z",
	"glmv",
	"gpt",
	"gpt-codex",
	"gpt-codex-mini",
	"gpt-codex-spark",
	"gpt-image",
	"gpt-mini",
	"gpt-nano",
	"gpt-oss",
	"gpt-pro",
	"granite",
	"grok",
	"grok-beta",
	"grok-vision",
	"groq",
	"hermes",
	"hunyuan",
	"ideogram",
	"imagen",
	"indictrans",
	"intellect",
	"jais",
	"jamba",
	"kat-coder",
	"kimi",
	"kimi-free",
	"kimi-thinking",
	"ling",
	"liquid",
	"llama",
	"longcat",
	"lucid",
	"lyria",
	"m2m",
	"magistral",
	"magistral-medium",
	"magistral-small",
	"mai",
	"melotts",
	"mercury",
	"mimo",
	"mimo-flash-free",
	"mimo-omni",
	"mimo-omni-free",
	"mimo-pro",
	"mimo-pro-free",
	"minimax",
	"minimax-free",
	"minimax-m2.5",
	"minimax-m2.7",
	"ministral",
	"mistral",
	"mistral-embed",
	"mistral-large",
	"mistral-medium",
	"mistral-nemo",
	"mistral-small",
	"mixtral",
	"mm-poly",
	"model-router",
	"morph",
	"nano-banana",
	"nemoretriever",
	"nemotron",
	"nemotron-free",
	"nousresearch",
	"nova",
	"nova-lite",
	"nova-micro",
	"nova-pro",
	"o",
	"o-mini",
	"o-pro",
	"opengvlab",
	"osmosis",
	"palmyra",
	"pangu",
	"parakeet",
	"phi",
	"pixtral",
	"plamo",
	"qvq",
	"qwen",
	"qwen-free",
	"qwerky",
	"ray",
	"recraft",
	"rednote",
	"ring",
	"rnj",
	"runway",
	"seed",
	"skywork",
	"smart-turn",
	"solar-mini",
	"solar-pro",
	"sonar",
	"sonar-deep-research",
	"sonar-pro",
	"sonar-reasoning",
	"sora",
	"sourceful",
	"stable-diffusion",
	"step",
	"tako",
	"text-embedding",
	"titan-embed",
	"tngtech",
	"topazlabs",
	"trinity",
	"trinity-mini",
	"unsloth",
	"v0",
	"venice",
	"veo",
	"voxtral",
	"voyage",
	"whisper",
	"yi",
}

// Families returns all known Family values as a defensive copy.
func Families() []Family {
	out := make([]Family, len(allFamilies))
	copy(out, allFamilies[:])
	return out
}
