// Code generated by bestiary-gen. DO NOT EDIT.
//go:generate go run ./cmd/bestiary-gen

package bestiary

// Model_* constants provide compile-time references to every eligible model
// in the static model registry. Names follow the pattern:
//
//	Model_<Provider>_<Family>_<Variant>_<Date>?
//
// where each component uses the same casing rules as Provider and Family
// constants. Underscores separate components; within-component characters
// are preserved (e.g. "4o" stays "4o", not "4_o").
//
// NOTE: This file is auto-generated by cmd/bestiary-gen.
// Run `go generate ./...` to regenerate with the full constant set.
// The current stub has zero constants; ModelIDs() returns nil.

// allModelConstants is the complete list of generated Model_* constants.
// Empty until generated by cmd/bestiary-gen with --generate-constants flag.
var allModelConstants = [...]ModelID{}

// ModelIDs returns all generated Model_* constant values as a defensive copy.
// Mutating the returned slice does not affect future calls.
// See Models() in registry.go for the full ModelInfo slice.
func ModelIDs() []ModelID {
	out := make([]ModelID, len(allModelConstants))
	copy(out, allModelConstants[:])
	return out
}
