// Code generated by bestiary-gen. DO NOT EDIT.

package bestiary

const (
	Provider302AI                  Provider = "302ai"
	ProviderAbacus                 Provider = "abacus"
	ProviderAIHubMix               Provider = "aihubmix"
	ProviderAlibaba                Provider = "alibaba"
	ProviderAlibabaCN              Provider = "alibaba-cn"
	ProviderAlibabaCodingPlan      Provider = "alibaba-coding-plan"
	ProviderAlibabaCodingPlanCN    Provider = "alibaba-coding-plan-cn"
	ProviderAmazonBedrock          Provider = "amazon-bedrock"
	ProviderAnthropic              Provider = "anthropic"
	ProviderAzure                  Provider = "azure"
	ProviderAzureCognitiveServices Provider = "azure-cognitive-services"
	ProviderBailing                Provider = "bailing"
	ProviderBaseten                Provider = "baseten"
	ProviderBerget                 Provider = "berget"
	ProviderCerebras               Provider = "cerebras"
	ProviderChutes                 Provider = "chutes"
	ProviderClarifai               Provider = "clarifai"
	ProviderCloudFerroSherlock     Provider = "cloudferro-sherlock"
	ProviderCloudflareAIGateway    Provider = "cloudflare-ai-gateway"
	ProviderCloudflareWorkersAI    Provider = "cloudflare-workers-ai"
	ProviderCohere                 Provider = "cohere"
	ProviderCortecs                Provider = "cortecs"
	ProviderDeepinfra              Provider = "deepinfra"
	ProviderDeepSeek               Provider = "deepseek"
	ProviderDInference             Provider = "dinference"
	ProviderDrun                   Provider = "drun"
	ProviderEvroc                  Provider = "evroc"
	ProviderFastRouter             Provider = "fastrouter"
	ProviderFireworksAI            Provider = "fireworks-ai"
	ProviderFirmware               Provider = "firmware"
	ProviderFriendli               Provider = "friendli"
	ProviderGitHubCopilot          Provider = "github-copilot"
	ProviderGitHubModels           Provider = "github-models"
	ProviderGitLab                 Provider = "gitlab"
	ProviderGoogle                 Provider = "google"
	ProviderGoogleVertex           Provider = "google-vertex"
	ProviderGoogleVertexAnthropic  Provider = "google-vertex-anthropic"
	ProviderGroq                   Provider = "groq"
	ProviderHelicone               Provider = "helicone"
	ProviderHuggingface            Provider = "huggingface"
	ProviderIflowcn                Provider = "iflowcn"
	ProviderInception              Provider = "inception"
	ProviderInference              Provider = "inference"
	ProviderIONet                  Provider = "io-net"
	ProviderJiekou                 Provider = "jiekou"
	ProviderKilo                   Provider = "kilo"
	ProviderKimiForCoding          Provider = "kimi-for-coding"
	ProviderKUAECloudCodingPlan    Provider = "kuae-cloud-coding-plan"
	ProviderLlama                  Provider = "llama"
	ProviderLlmgateway             Provider = "llmgateway"
	ProviderLMStudio               Provider = "lmstudio"
	ProviderLucidQuery             Provider = "lucidquery"
	ProviderMeganova               Provider = "meganova"
	ProviderMiniMax                Provider = "minimax"
	ProviderMiniMaxCN              Provider = "minimax-cn"
	ProviderMiniMaxCNCodingPlan    Provider = "minimax-cn-coding-plan"
	ProviderMiniMaxCodingPlan      Provider = "minimax-coding-plan"
	ProviderMistral                Provider = "mistral"
	ProviderMixlayer               Provider = "mixlayer"
	ProviderMoark                  Provider = "moark"
	ProviderModelScope             Provider = "modelscope"
	ProviderMoonshotai             Provider = "moonshotai"
	ProviderMoonshotaiCN           Provider = "moonshotai-cn"
	ProviderMorph                  Provider = "morph"
	ProviderNanoGPT                Provider = "nano-gpt"
	ProviderNebius                 Provider = "nebius"
	ProviderNova                   Provider = "nova"
	ProviderNovitaAI               Provider = "novita-ai"
	ProviderNvidia                 Provider = "nvidia"
	ProviderOllamaCloud            Provider = "ollama-cloud"
	ProviderOpenAI                 Provider = "openai"
	ProviderOpenCode               Provider = "opencode"
	ProviderOpenCodeGo             Provider = "opencode-go"
	ProviderOpenRouter             Provider = "openrouter"
	ProviderOVHcloud               Provider = "ovhcloud"
	ProviderPerplexity             Provider = "perplexity"
	ProviderPerplexityAgent        Provider = "perplexity-agent"
	ProviderPoe                    Provider = "poe"
	ProviderPrivatemodeAI          Provider = "privatemode-ai"
	ProviderQiHangAI               Provider = "qihang-ai"
	ProviderQiniuAI                Provider = "qiniu-ai"
	ProviderRequesty               Provider = "requesty"
	ProviderSAPAICore              Provider = "sap-ai-core"
	ProviderScaleway               Provider = "scaleway"
	ProviderSiliconFlow            Provider = "siliconflow"
	ProviderSiliconFlowCN          Provider = "siliconflow-cn"
	ProviderSTACKIT                Provider = "stackit"
	ProviderStepFun                Provider = "stepfun"
	ProviderSubmodel               Provider = "submodel"
	ProviderSynthetic              Provider = "synthetic"
	ProviderTencentCodingPlan      Provider = "tencent-coding-plan"
	ProviderTheGridAI              Provider = "the-grid-ai"
	ProviderTogetherai             Provider = "togetherai"
	ProviderUpstage                Provider = "upstage"
	ProviderV0                     Provider = "v0"
	ProviderVenice                 Provider = "venice"
	ProviderVercel                 Provider = "vercel"
	ProviderVivgrid                Provider = "vivgrid"
	ProviderVultr                  Provider = "vultr"
	ProviderWandb                  Provider = "wandb"
	ProviderXAI                    Provider = "xai"
	ProviderXiaomi                 Provider = "xiaomi"
	ProviderXiaomiTokenPlanAMS     Provider = "xiaomi-token-plan-ams"
	ProviderXiaomiTokenPlanCN      Provider = "xiaomi-token-plan-cn"
	ProviderXiaomiTokenPlanSGP     Provider = "xiaomi-token-plan-sgp"
	ProviderZai                    Provider = "zai"
	ProviderZaiCodingPlan          Provider = "zai-coding-plan"
	ProviderZenMux                 Provider = "zenmux"
	ProviderZhipuai                Provider = "zhipuai"
	ProviderZhipuaiCodingPlan      Provider = "zhipuai-coding-plan"
)

// knownProviders contains all Provider constants from the models.dev API
// plus ProviderLocal. Used by IsKnown() and Providers().
var knownProviders = [...]Provider{
	Provider302AI,
	ProviderAbacus,
	ProviderAIHubMix,
	ProviderAlibaba,
	ProviderAlibabaCN,
	ProviderAlibabaCodingPlan,
	ProviderAlibabaCodingPlanCN,
	ProviderAmazonBedrock,
	ProviderAnthropic,
	ProviderAzure,
	ProviderAzureCognitiveServices,
	ProviderBailing,
	ProviderBaseten,
	ProviderBerget,
	ProviderCerebras,
	ProviderChutes,
	ProviderClarifai,
	ProviderCloudFerroSherlock,
	ProviderCloudflareAIGateway,
	ProviderCloudflareWorkersAI,
	ProviderCohere,
	ProviderCortecs,
	ProviderDeepinfra,
	ProviderDeepSeek,
	ProviderDInference,
	ProviderDrun,
	ProviderEvroc,
	ProviderFastRouter,
	ProviderFireworksAI,
	ProviderFirmware,
	ProviderFriendli,
	ProviderGitHubCopilot,
	ProviderGitHubModels,
	ProviderGitLab,
	ProviderGoogle,
	ProviderGoogleVertex,
	ProviderGoogleVertexAnthropic,
	ProviderGroq,
	ProviderHelicone,
	ProviderHuggingface,
	ProviderIflowcn,
	ProviderInception,
	ProviderInference,
	ProviderIONet,
	ProviderJiekou,
	ProviderKilo,
	ProviderKimiForCoding,
	ProviderKUAECloudCodingPlan,
	ProviderLlama,
	ProviderLlmgateway,
	ProviderLMStudio,
	ProviderLucidQuery,
	ProviderMeganova,
	ProviderMiniMax,
	ProviderMiniMaxCN,
	ProviderMiniMaxCNCodingPlan,
	ProviderMiniMaxCodingPlan,
	ProviderMistral,
	ProviderMixlayer,
	ProviderMoark,
	ProviderModelScope,
	ProviderMoonshotai,
	ProviderMoonshotaiCN,
	ProviderMorph,
	ProviderNanoGPT,
	ProviderNebius,
	ProviderNova,
	ProviderNovitaAI,
	ProviderNvidia,
	ProviderOllamaCloud,
	ProviderOpenAI,
	ProviderOpenCode,
	ProviderOpenCodeGo,
	ProviderOpenRouter,
	ProviderOVHcloud,
	ProviderPerplexity,
	ProviderPerplexityAgent,
	ProviderPoe,
	ProviderPrivatemodeAI,
	ProviderQiHangAI,
	ProviderQiniuAI,
	ProviderRequesty,
	ProviderSAPAICore,
	ProviderScaleway,
	ProviderSiliconFlow,
	ProviderSiliconFlowCN,
	ProviderSTACKIT,
	ProviderStepFun,
	ProviderSubmodel,
	ProviderSynthetic,
	ProviderTencentCodingPlan,
	ProviderTheGridAI,
	ProviderTogetherai,
	ProviderUpstage,
	ProviderV0,
	ProviderVenice,
	ProviderVercel,
	ProviderVivgrid,
	ProviderVultr,
	ProviderWandb,
	ProviderXAI,
	ProviderXiaomi,
	ProviderXiaomiTokenPlanAMS,
	ProviderXiaomiTokenPlanCN,
	ProviderXiaomiTokenPlanSGP,
	ProviderZai,
	ProviderZaiCodingPlan,
	ProviderZenMux,
	ProviderZhipuai,
	ProviderZhipuaiCodingPlan,
	ProviderLocal, // bestiary-specific, always last
}
