// Code generated by bestiary-gen. DO NOT EDIT.

package bestiary

const (
	Provider302AI                  Provider = "302ai"
	ProviderAbacus                 Provider = "abacus"
	ProviderAbliterationAI         Provider = "abliteration-ai"
	ProviderAgentRouter            Provider = "agentrouter"
	ProviderAgnes                  Provider = "agnes"
	ProviderAIRouter               Provider = "ai-router"
	ProviderAiand                  Provider = "aiand"
	ProviderAIHubMix               Provider = "aihubmix"
	ProviderAixy                   Provider = "aixy"
	ProviderAkiIO                  Provider = "aki-io"
	ProviderAlibaba                Provider = "alibaba"
	ProviderAlibabaCN              Provider = "alibaba-cn"
	ProviderAlibabaCodingPlan      Provider = "alibaba-coding-plan"
	ProviderAlibabaCodingPlanCN    Provider = "alibaba-coding-plan-cn"
	ProviderAlibabaTokenPlan       Provider = "alibaba-token-plan"
	ProviderAlibabaTokenPlanCN     Provider = "alibaba-token-plan-cn"
	ProviderAmazonBedrock          Provider = "amazon-bedrock"
	ProviderAmbient                Provider = "ambient"
	ProviderAMD                    Provider = "amd"
	ProviderAnthropic              Provider = "anthropic"
	ProviderAnyAPI                 Provider = "anyapi"
	ProviderArcee                  Provider = "arcee"
	ProviderAtomicChat             Provider = "atomic-chat"
	ProviderAuriko                 Provider = "auriko"
	ProviderAzure                  Provider = "azure"
	ProviderAzureCognitiveServices Provider = "azure-cognitive-services"
	ProviderBailing                Provider = "bailing"
	ProviderBaseten                Provider = "baseten"
	ProviderBerget                 Provider = "berget"
	ProviderBlueclaw               Provider = "blueclaw"
	ProviderCerebras               Provider = "cerebras"
	ProviderChutes                 Provider = "chutes"
	ProviderClarifai               Provider = "clarifai"
	ProviderClaudinio              Provider = "claudinio"
	ProviderClinePass              Provider = "cline-pass"
	ProviderCloudFerroSherlock     Provider = "cloudferro-sherlock"
	ProviderCloudflareAIGateway    Provider = "cloudflare-ai-gateway"
	ProviderCloudflareWorkersAI    Provider = "cloudflare-workers-ai"
	ProviderCohere                 Provider = "cohere"
	ProviderCoralBricks            Provider = "coralbricks"
	ProviderCortecs                Provider = "cortecs"
	ProviderCrof                   Provider = "crof"
	ProviderCrossModel             Provider = "crossmodel"
	ProviderCrusoe                 Provider = "crusoe"
	ProviderDaoXE                  Provider = "daoxe"
	ProviderDatabricks             Provider = "databricks"
	ProviderDeepInfra              Provider = "deepinfra"
	ProviderDeepSeek               Provider = "deepseek"
	ProviderDigitalOcean           Provider = "digitalocean"
	ProviderDInference             Provider = "dinference"
	ProviderDrun                   Provider = "drun"
	ProviderEBCloud                Provider = "ebcloud"
	ProviderEcho                   Provider = "echo"
	ProviderEdenai                 Provider = "edenai"
	ProviderEmpirioLabs            Provider = "empiriolabs"
	ProviderEvroc                  Provider = "evroc"
	ProviderFastRouter             Provider = "fastrouter"
	ProviderFireworksAI            Provider = "fireworks-ai"
	ProviderFreeModel              Provider = "freemodel"
	ProviderFriendli               Provider = "friendli"
	ProviderFrogBot                Provider = "frogbot"
	ProviderGitHubCopilot          Provider = "github-copilot"
	ProviderGitLab                 Provider = "gitlab"
	ProviderGMICloud               Provider = "gmicloud"
	ProviderGoogle                 Provider = "google"
	ProviderGoogleVertex           Provider = "google-vertex"
	ProviderGoogleVertexAnthropic  Provider = "google-vertex-anthropic"
	ProviderGreenPT                Provider = "greenpt"
	ProviderGroq                   Provider = "groq"
	ProviderHelicone               Provider = "helicone"
	ProviderHetzner                Provider = "hetzner"
	ProviderHpcAI                  Provider = "hpc-ai"
	ProviderHuggingFace            Provider = "huggingface"
	ProviderHyper                  Provider = "hyper"
	ProvideriFlowCN                Provider = "iflowcn"
	ProviderImpossibl              Provider = "impossibl"
	ProviderInception              Provider = "inception"
	ProviderInceptron              Provider = "inceptron"
	ProviderInference              Provider = "inference"
	ProviderInferX                 Provider = "inferx"
	ProviderInfomaniak             Provider = "infomaniak"
	ProviderIONet                  Provider = "io-net"
	ProviderIteraCompute           Provider = "iteracompute"
	ProviderJalapeno               Provider = "jalapeno"
	ProviderJiekou                 Provider = "jiekou"
	ProviderKenari                 Provider = "kenari"
	ProviderKilo                   Provider = "kilo"
	ProviderKimiForCoding          Provider = "kimi-for-coding"
	ProviderKosmik                 Provider = "kosmik"
	ProviderKUAECloudCodingPlan    Provider = "kuae-cloud-coding-plan"
	ProviderLilac                  Provider = "lilac"
	ProviderLlama                  Provider = "llama"
	ProviderLlmGateway             Provider = "llmgateway"
	ProviderLlmGatewayProviders    Provider = "llmgateway-providers"
	ProviderLlmtech                Provider = "llmtech"
	ProviderLLMTR                  Provider = "llmtr"
	ProviderLMStudio               Provider = "lmstudio"
	ProviderLongCat                Provider = "longcat"
	ProviderLucidQuery             Provider = "lucidquery"
	ProviderLynkr                  Provider = "lynkr"
	ProviderMeganova               Provider = "meganova"
	ProviderMergeGateway           Provider = "merge-gateway"
	ProviderMeta                   Provider = "meta"
	ProviderMiniMax                Provider = "minimax"
	ProviderMiniMaxCN              Provider = "minimax-cn"
	ProviderMiniMaxCNCodingPlan    Provider = "minimax-cn-coding-plan"
	ProviderMiniMaxCodingPlan      Provider = "minimax-coding-plan"
	ProviderMistral                Provider = "mistral"
	ProviderMixlayer               Provider = "mixlayer"
	ProviderMoark                  Provider = "moark"
	ProviderModal                  Provider = "modal"
	ProviderModelOracleAI          Provider = "model-oracle-ai"
	ProviderModelis                Provider = "modelis"
	ProviderModelScope             Provider = "modelscope"
	ProviderMoonshotAI             Provider = "moonshotai"
	ProviderMoonshotAICN           Provider = "moonshotai-cn"
	ProviderMorph                  Provider = "morph"
	ProviderNanoGPT                Provider = "nano-gpt"
	ProviderNearAI                 Provider = "nearai"
	ProviderNebius                 Provider = "nebius"
	ProviderNeon                   Provider = "neon"
	ProviderNeoSmith               Provider = "neosmith"
	ProviderNeuralwatt             Provider = "neuralwatt"
	ProviderNova                   Provider = "nova"
	ProviderNovitaAI               Provider = "novita-ai"
	ProviderNvidia                 Provider = "nvidia"
	ProviderOfox                   Provider = "ofox"
	ProviderOllamaCloud            Provider = "ollama-cloud"
	ProviderOpenAI                 Provider = "openai"
	ProviderOpenCode               Provider = "opencode"
	ProviderOpenCodeGo             Provider = "opencode-go"
	ProviderOpenRouter             Provider = "openrouter"
	ProviderOpper                  Provider = "opper"
	ProviderOrcaRouter             Provider = "orcarouter"
	ProviderOVHcloud               Provider = "ovhcloud"
	ProviderPendra                 Provider = "pendra"
	ProviderPerplexity             Provider = "perplexity"
	ProviderPerplexityAgent        Provider = "perplexity-agent"
	ProviderPioneer                Provider = "pioneer"
	ProviderPoe                    Provider = "poe"
	ProviderPoolside               Provider = "poolside"
	ProviderPrivatemodeAI          Provider = "privatemode-ai"
	ProviderQiHangAI               Provider = "qihang-ai"
	ProviderQiniuAI                Provider = "qiniu-ai"
	ProviderQVAC                   Provider = "qvac"
	ProviderRegoloAI               Provider = "regolo-ai"
	ProviderRequesty               Provider = "requesty"
	ProviderRoutingRun             Provider = "routing-run"
	ProviderRunInfra               Provider = "runinfra"
	ProviderSakana                 Provider = "sakana"
	ProviderSaladCloud             Provider = "salad-cloud"
	ProviderSAPAICore              Provider = "sap-ai-core"
	ProviderSarvam                 Provider = "sarvam"
	ProviderScaleway               Provider = "scaleway"
	ProviderSCNetTokenPlan         Provider = "scnet-token-plan"
	ProviderScxAI                  Provider = "scx-ai"
	ProviderSiliconFlow            Provider = "siliconflow"
	ProviderSiliconFlowCN          Provider = "siliconflow-cn"
	ProviderSnowflakeCortex        Provider = "snowflake-cortex"
	ProviderSTACKIT                Provider = "stackit"
	ProviderStandardcompute        Provider = "standardcompute"
	ProviderStepFun                Provider = "stepfun"
	ProviderStepFunAI              Provider = "stepfun-ai"
	ProviderStepFunAIStepPlan      Provider = "stepfun-ai-step-plan"
	ProviderStepFunStepPlan        Provider = "stepfun-step-plan"
	ProviderSubconscious           Provider = "subconscious"
	ProviderSubmodel               Provider = "submodel"
	ProviderSynthetic              Provider = "synthetic"
	ProviderTencentCodingPlan      Provider = "tencent-coding-plan"
	ProviderTencentTokenPlan       Provider = "tencent-token-plan"
	ProviderTencentTokenHub        Provider = "tencent-tokenhub"
	ProviderTensorX                Provider = "tensorx"
	ProviderTheGridAI              Provider = "the-grid-ai"
	ProviderThinkingmachines       Provider = "thinkingmachines"
	ProviderTinfoil                Provider = "tinfoil"
	ProviderTogetherAI             Provider = "togetherai"
	ProviderTokenGo                Provider = "tokengo"
	ProviderTrustedRouter          Provider = "trustedrouter"
	ProviderUmansAI                Provider = "umans-ai"
	ProviderUmansAICodingPlan      Provider = "umans-ai-coding-plan"
	ProviderUnoRouter              Provider = "unorouter"
	ProviderUpstage                Provider = "upstage"
	ProviderV0                     Provider = "v0"
	ProviderVenice                 Provider = "venice"
	ProviderVercel                 Provider = "vercel"
	ProviderVivgrid                Provider = "vivgrid"
	ProviderVolcengine             Provider = "volcengine"
	ProviderVultr                  Provider = "vultr"
	ProviderWaferAI                Provider = "wafer.ai"
	ProviderWandb                  Provider = "wandb"
	ProviderWatsonx                Provider = "watsonx"
	ProviderxAI                    Provider = "xai"
	ProviderXiaomi                 Provider = "xiaomi"
	ProviderXiaomiTokenPlanAMS     Provider = "xiaomi-token-plan-ams"
	ProviderXiaomiTokenPlanCN      Provider = "xiaomi-token-plan-cn"
	ProviderXiaomiTokenPlanSGP     Provider = "xiaomi-token-plan-sgp"
	ProviderXpersona               Provider = "xpersona"
	ProviderZai                    Provider = "zai"
	ProviderZaiCodingPlan          Provider = "zai-coding-plan"
	ProviderZeldoc                 Provider = "zeldoc"
	ProviderZenifra                Provider = "zenifra"
	ProviderZenMux                 Provider = "zenmux"
	ProviderZhipuai                Provider = "zhipuai"
	ProviderZhipuaiCodingPlan      Provider = "zhipuai-coding-plan"
)

// knownProviders contains all Provider constants from the models.dev API
// plus ProviderLocal. Used by IsKnown() and Providers().
var knownProviders = [...]Provider{
	Provider302AI,
	ProviderAbacus,
	ProviderAbliterationAI,
	ProviderAgentRouter,
	ProviderAgnes,
	ProviderAIRouter,
	ProviderAiand,
	ProviderAIHubMix,
	ProviderAixy,
	ProviderAkiIO,
	ProviderAlibaba,
	ProviderAlibabaCN,
	ProviderAlibabaCodingPlan,
	ProviderAlibabaCodingPlanCN,
	ProviderAlibabaTokenPlan,
	ProviderAlibabaTokenPlanCN,
	ProviderAmazonBedrock,
	ProviderAmbient,
	ProviderAMD,
	ProviderAnthropic,
	ProviderAnyAPI,
	ProviderArcee,
	ProviderAtomicChat,
	ProviderAuriko,
	ProviderAzure,
	ProviderAzureCognitiveServices,
	ProviderBailing,
	ProviderBaseten,
	ProviderBerget,
	ProviderBlueclaw,
	ProviderCerebras,
	ProviderChutes,
	ProviderClarifai,
	ProviderClaudinio,
	ProviderClinePass,
	ProviderCloudFerroSherlock,
	ProviderCloudflareAIGateway,
	ProviderCloudflareWorkersAI,
	ProviderCohere,
	ProviderCoralBricks,
	ProviderCortecs,
	ProviderCrof,
	ProviderCrossModel,
	ProviderCrusoe,
	ProviderDaoXE,
	ProviderDatabricks,
	ProviderDeepInfra,
	ProviderDeepSeek,
	ProviderDigitalOcean,
	ProviderDInference,
	ProviderDrun,
	ProviderEBCloud,
	ProviderEcho,
	ProviderEdenai,
	ProviderEmpirioLabs,
	ProviderEvroc,
	ProviderFastRouter,
	ProviderFireworksAI,
	ProviderFreeModel,
	ProviderFriendli,
	ProviderFrogBot,
	ProviderGitHubCopilot,
	ProviderGitLab,
	ProviderGMICloud,
	ProviderGoogle,
	ProviderGoogleVertex,
	ProviderGoogleVertexAnthropic,
	ProviderGreenPT,
	ProviderGroq,
	ProviderHelicone,
	ProviderHetzner,
	ProviderHpcAI,
	ProviderHuggingFace,
	ProviderHyper,
	ProvideriFlowCN,
	ProviderImpossibl,
	ProviderInception,
	ProviderInceptron,
	ProviderInference,
	ProviderInferX,
	ProviderInfomaniak,
	ProviderIONet,
	ProviderIteraCompute,
	ProviderJalapeno,
	ProviderJiekou,
	ProviderKenari,
	ProviderKilo,
	ProviderKimiForCoding,
	ProviderKosmik,
	ProviderKUAECloudCodingPlan,
	ProviderLilac,
	ProviderLlama,
	ProviderLlmGateway,
	ProviderLlmGatewayProviders,
	ProviderLlmtech,
	ProviderLLMTR,
	ProviderLMStudio,
	ProviderLongCat,
	ProviderLucidQuery,
	ProviderLynkr,
	ProviderMeganova,
	ProviderMergeGateway,
	ProviderMeta,
	ProviderMiniMax,
	ProviderMiniMaxCN,
	ProviderMiniMaxCNCodingPlan,
	ProviderMiniMaxCodingPlan,
	ProviderMistral,
	ProviderMixlayer,
	ProviderMoark,
	ProviderModal,
	ProviderModelOracleAI,
	ProviderModelis,
	ProviderModelScope,
	ProviderMoonshotAI,
	ProviderMoonshotAICN,
	ProviderMorph,
	ProviderNanoGPT,
	ProviderNearAI,
	ProviderNebius,
	ProviderNeon,
	ProviderNeoSmith,
	ProviderNeuralwatt,
	ProviderNova,
	ProviderNovitaAI,
	ProviderNvidia,
	ProviderOfox,
	ProviderOllamaCloud,
	ProviderOpenAI,
	ProviderOpenCode,
	ProviderOpenCodeGo,
	ProviderOpenRouter,
	ProviderOpper,
	ProviderOrcaRouter,
	ProviderOVHcloud,
	ProviderPendra,
	ProviderPerplexity,
	ProviderPerplexityAgent,
	ProviderPioneer,
	ProviderPoe,
	ProviderPoolside,
	ProviderPrivatemodeAI,
	ProviderQiHangAI,
	ProviderQiniuAI,
	ProviderQVAC,
	ProviderRegoloAI,
	ProviderRequesty,
	ProviderRoutingRun,
	ProviderRunInfra,
	ProviderSakana,
	ProviderSaladCloud,
	ProviderSAPAICore,
	ProviderSarvam,
	ProviderScaleway,
	ProviderSCNetTokenPlan,
	ProviderScxAI,
	ProviderSiliconFlow,
	ProviderSiliconFlowCN,
	ProviderSnowflakeCortex,
	ProviderSTACKIT,
	ProviderStandardcompute,
	ProviderStepFun,
	ProviderStepFunAI,
	ProviderStepFunAIStepPlan,
	ProviderStepFunStepPlan,
	ProviderSubconscious,
	ProviderSubmodel,
	ProviderSynthetic,
	ProviderTencentCodingPlan,
	ProviderTencentTokenPlan,
	ProviderTencentTokenHub,
	ProviderTensorX,
	ProviderTheGridAI,
	ProviderThinkingmachines,
	ProviderTinfoil,
	ProviderTogetherAI,
	ProviderTokenGo,
	ProviderTrustedRouter,
	ProviderUmansAI,
	ProviderUmansAICodingPlan,
	ProviderUnoRouter,
	ProviderUpstage,
	ProviderV0,
	ProviderVenice,
	ProviderVercel,
	ProviderVivgrid,
	ProviderVolcengine,
	ProviderVultr,
	ProviderWaferAI,
	ProviderWandb,
	ProviderWatsonx,
	ProviderxAI,
	ProviderXiaomi,
	ProviderXiaomiTokenPlanAMS,
	ProviderXiaomiTokenPlanCN,
	ProviderXiaomiTokenPlanSGP,
	ProviderXpersona,
	ProviderZai,
	ProviderZaiCodingPlan,
	ProviderZeldoc,
	ProviderZenifra,
	ProviderZenMux,
	ProviderZhipuai,
	ProviderZhipuaiCodingPlan,
	ProviderLocal, // bestiary-specific, always last
}
